// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0N8PocrQ7ZRfGJ6H4T4UVAMhClu3Yjo',
    appId: '1:252472073589:web:b9981d306f3335ce1fc73c',
    messagingSenderId: '252472073589',
    projectId: 'eco-credit-app-842f8',
    authDomain: 'eco-credit-app-842f8.firebaseapp.com',
    storageBucket: 'eco-credit-app-842f8.firebasestorage.app',
    measurementId: 'G-5QYBEGBWSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMWfBZIj38Uug2ii9w1ITIfFnSV-6ASDQ',
    appId: '1:252472073589:android:5fdadd811f7a68321fc73c',
    messagingSenderId: '252472073589',
    projectId: 'eco-credit-app-842f8',
    storageBucket: 'eco-credit-app-842f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk0ff7frYxrMvopiILMt6tat2R5A-qi4o',
    appId: '1:252472073589:ios:c372c4abf16a65f41fc73c',
    messagingSenderId: '252472073589',
    projectId: 'eco-credit-app-842f8',
    storageBucket: 'eco-credit-app-842f8.firebasestorage.app',
    iosBundleId: 'com.example.ecoCreditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk0ff7frYxrMvopiILMt6tat2R5A-qi4o',
    appId: '1:252472073589:ios:c372c4abf16a65f41fc73c',
    messagingSenderId: '252472073589',
    projectId: 'eco-credit-app-842f8',
    storageBucket: 'eco-credit-app-842f8.firebasestorage.app',
    iosBundleId: 'com.example.ecoCreditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq0N8PocrQ7ZRfGJ6H4T4UVAMhClu3Yjo',
    appId: '1:252472073589:web:24142b68d78dd9fa1fc73c',
    messagingSenderId: '252472073589',
    projectId: 'eco-credit-app-842f8',
    authDomain: 'eco-credit-app-842f8.firebaseapp.com',
    storageBucket: 'eco-credit-app-842f8.firebasestorage.app',
    measurementId: 'G-P966XL5LZR',
  );
}
